[theme]
primaryColor = "#FF4B4B"
# backgroundColor = "#10344b"
backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableStaticServing = true
